### ISSUE TITLE
When inspecting in a MiBrowser, open the MiInspectorBrowser

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#271]
we don't want to leave Moose environment

**Comment by jordanmontt** [comment]
There is already the `MiInspectorCommand` that opens the MooseInspector. That is used in all browsers in this button: 
![Screenshot 2021-09-02 at 18 08 16](https://user-images.githubusercontent.com/33934979/131878851-9e3ffabd-25bf-4e79-9c0d-f47c79b8caad.png) This is working for all MooseIDE tools.

Also it is used when you right click on the ModelsBrowser and it is working: 
![Screenshot 2021-09-02 at 18 09 43](https://user-images.githubusercontent.com/33934979/131879091-963bbe16-a0a7-4841-bc56-12b60f873bbf.png)

It's also used when you right click on the logger browser
![Screenshot 2021-09-02 at 18 10 36](https://user-images.githubusercontent.com/33934979/131879226-5ae134f5-8a61-4fb0-a35f-e6e9a76dfd86.png)
But for this one it dies. That is because the command has the followinf code: `MiInspectorBrowser inspect: selectedItem forBuses: self context buses` and, in the logger browser when you right click you are using the class `MibusLogsList` and not `MiLoggerBrowser` and the `MibusLogsList` *does not know what is the bus.*

So we have two solutions for this:
1. add an if in the command (not nice and not the best solution)
2. remove this option when you are right clicking. I this that this is the best because you can use the button that is in the common tool bar for all moose browser (see first image).

Actually, I think that the right click funtionality is not need because you already have the button in the first image

**Comment by jordanmontt** [comment]
I don't know if I have been clear. What do you think @ClotildeToullec 

I think that this issue can be closed. The only thing that we have to fix is to remove the right-click inspect on the logger browser.

**Comment by ClotildeToullec** [comment]
I'm not sure we want to remove the right-click inspect.
It's not very intuitive to have to select an item them go back to the toolbar to click inspect.

I would also like to add a shortcut to inspect any selected entity in any browser. I did it for the playground, which is a bit special, but I would love to use keyboard instead of clicks when navigating Moose.

**Comment by jordanmontt** [comment]
I think that is more intuitive to click on the inspect button on the toolbar
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33934979/132021433-0c0c7253-1ce4-4b57-be0f-4914e38859ed.gif)

**Comment by jordanmontt** [comment]
And did you add the moose inspector button to the repo? I also that is a good idea to have a shortcut
