### ISSUE TITLE
hierarchical result pane of QueryBrowser

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#289]
bottom list is currently sorted by "kind of entities" 

We want also a hierarchical tree of entities:
```
  > package1
    > class11
	> class12
	  method121
	  method122
  > package2
```
Both view could be in two different tabs for this pane
(note: there is already a tab for the source code of the query)

**Comment by ClotildeToullec** [comment]
Related to #290

**Comment by jordanmontt** [comment]
Yes, I agree that this should be a widget that we could reuse

**Comment by anneetien** [comment]
still relevant ?

**Comment by ClotildeToullec** [comment]
I think yes.

**Comment by ClotildeToullec** [comment]
Giving a thought about this, I'm not sure anymore.
In your example @NicolasAnquetil, what is the result of the query?
- Is it the packages and we can expand them to see their children, even if they are not directly the result of the query?
- Is it the leaf entities and we see them in their container, even if they are not directly the result of the query?
- Is it all the displayed entities?

In the first 2 possibilities, I am against doing this because the result pane should show only the query result.
As to the third one, I'm not sure it happens a lot to have a query result with different types of entities that happen to be children of one another.

**Comment by NicolasAnquetil** [comment]
OK, so yes the answer is the third one
now is it worth the effort? I am not sure
