### ISSUE TITLE
Bug in the demo of Clotilde (size query to compute classes without incoming links is not working)

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/MooseIDE#363]

**Comment by ClotildeToullec** [comment]
The problem comes from the implementation of the Result size query:
the inner query is considered alone and not as a child of its parent. This means the inner query is applied on the input of Result size query.

In the demo example, we had: 
- input: 1 AnnotationType (Deprecated)
- Q1: Relation #instances *--> 284 annotation instances*
	- Q2: Relation #annotatedEntities *--> 284 entities*
		- Q3: Type Classes *--> 28 classes*
			- Q4: Navigation all associations *--> 10 classes + 5 methods*
- Q5: Result of Q4 size = 0 *--> 1 AnnotationType*

Here, Q5 is applied on the input i.e. the annotation type, thus so is Q4 as inner query.

A correct use would have been: 
- input: 1 AnnotationType (Deprecated)
- Q1: Relation #instances *--> 284 annotation instances*
	- Q2: Relation #annotatedEntities *--> 284 entities*
		- Q3: Type Classes *--> 28 classes*
		**- Q5: Result of Q4 size = 0** ***--> 14 classes***
- Q4: Navigation all associations *--> 1 AnnotatedType* (This result is not important here)
