### ISSUE TITLE
Metamodels should have a description

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#42]
following on #38, in ImportModel window, the (drop down) list of metamodels could give the name and a short description

**Comment by badetitou** [comment]
I agree but, what is the description of the model?
Maybe we can generate the description in the metamodel generator as a comment and use the comment of the XXXModel class for the description?

**Comment by NicolasAnquetil** [comment]
The description is very simple:
This is a meata-model for java code
This meta-model is intended to be fully compatible with the old Famix metamodel
...

The idea is that  ImportModel window offers MANY possible metamodels, some of which look very similar one to the other

**Comment by anneetien** [comment]
Is it still relevant?

**Comment by anneetien** [comment]
No response. I believe it is no more relevant.

**Comment by fuhrmanator** [comment]
Sorry I'm late to see this (backlog of GitHub notifications). With my students, we run into problems with "versions" of metamodels (importer and Moose) being wrong. I wonder if a description could also include a version. I know I discussed with @NicolasAnquetil how it was managed, and it seems to be ad-hoc so maybe it could be useful to have versions. I think a model generated for a MM would also contain that version info, if that makes sense.

**Comment by NicolasAnquetil** [comment]
Yes this issue of meta-model version is annoying and we stumble on it once or twice.
It is not clear how to handle it properly?
Git tags? tests?
The problem is that we are a small team and we want it to be as light as possible.
We thought about automatic tests to check that a meta-model version is compatible with external tools...

**Comment by fuhrmanator** [comment]
For `ts2famix` I was thinking to put the version in the metamodel as an MM element. We can parse it from the `package.json` (there's a command in npm to manage semantic versioning). 

For the MM, the version would (should) come from the Pharo baseline. Although I've no idea yet how you get that data a run time to do checks. 

The versioning of ts2famix would have to be set manually to follow the version of the MM it supports, because (for now) it can't be loaded from a MM (the API is manually changed). On the other hand, since VerveineJ uses FameJava, if the MM had a version then VerveineJ would get it from the generated API (theoretically) and put that in its models. 

When Moose loads a model, it would warn about incompatibilities between MM and model, e.g., especially with major version differences.

Even if Moose doesn't check, when my students have problems with models loading in Moose, I can at least diagnose them if there's some "version" in a model from the parser, so I'm very likely to put at least the npm version somewhere in the .json file that is produced by ts2famix.

**Comment by NicolasAnquetil** [comment]
We always have a FamixXYZModel object.
The version information could go there ...
(and we would provide manually the information to the #generate method)
