### ISSUE TITLE
Do a pass on Queries Browser to improve the speed

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#61]
Opening the query creator can be very slow when there is many entities.
This should be optimized.

**Comment by jecisc** [comment]
One thing I found is that FQAbstractNavigationDirection class>>#availableAssociationsFor: is called 7 times when we open the browser. 

It should be called only once and the result stored. 

Probably not the main bottleneck but would still be nice to optimize

**Comment by jordanmontt** [comment]
@ClotildeToullec

**Comment by NicolasAnquetil** [comment]
Why closing the issue?
The problem still exist and it would be important to investigate it

**Comment by NicolasAnquetil** [comment]
OK, so apparently this could be because you are closing all issues related to old query browser.
This is a good idea, but it would be nice to recreate this one for the new query browser

**Comment by jordanmontt** [comment]
Yes, I was closing all issues relating to the old queries browser. But also I closed this issue because I think that is not a problem of the queries browser (neither the old or the new one) but a problem of all Midas tools. Because all Midas tools tend to be kind of slow.

Also we have this other GitHub issue that relates to the same problem: #67
