### ISSUE TITLE
ModelBrowser should inspect the entire model even if propagating non-stub entities

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#641]
Following #599, the ModelBrowser now propagates only non-stub entities by default

But when inspecting a model, this is long and it means we have a flat list of entities without the nice categories (allModelClasses, allModelMethods, ...)

So "Inspect" should probably ignore this option and always show the full model

**Comment by RomainDeg** [comment]
Furthermore, for #672, the sub-menu 'Utility' is disabled because the selected item on which the menu is opened is a MooseGroup and not a MooseModel (to verify it, you can also uncheck the 'Filter out stubs ?' setting, which will allow the sub-menu to be used again. The method called is MiModelUtilityCommand>>canBeExecuted).

Maybe it would be more interesting to apply the filter only for propagation, to fix both issues ?
