### ISSUE TITLE
Removing single entry from log doesn't remove it from Queries browser

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/MooseIDE#679]
Please forgive me if I'm misunderstanding how bus propagation works, but I think there is a bug.

1. Select a model
2. Propagate it to the default bus
3. Open the Queries browser and you will see the model's name in the window (below it's `emojiopoly1`).
4. Open the logger for the bus and delete the propagation entry (log). 
5. The Queries browser still shows the model is `emojiopoly1` (I think it should show nothing, as the bus should be empty, right?)
6. Open another Queries browser and it shows no context (no model) as the bus has nothing on it.

![Pharo_Q2DwLEVQzj](https://user-images.githubusercontent.com/7606540/175564491-30acdec2-9d12-4875-a632-dade768169c9.gif)

I also think there should be some way to "Inspect" the bus to see its current state. The Logger only shows "propagation events" (if I am understanding correctly) but not what is actually on the bus. I can assume that if all entries are deleted, the bus is empty. However, when there are multiple entries, which one is currently on the bus (the top one?). This is not intuitive to me.

**Comment by NicolasAnquetil** [comment]
The idea behind the logger is that it logs whatever passes on the bus., This is not an editor of the bus.
When you remove an entry in the logger, you just removed some local information the logger has. It has no effect on the bus.

And yes, the current state of the bus is the top entry of the logger. Except when you remove that last entry.

Now, can you describe the scenario where you want to know the current state of the bus?
May be we need some kind of new tool?

However, remember that MooseIDE is primarily intended for new users of Moose, to help them getting things done without having to learn all of Moose.
It is currently not aiming at allowing everybody to do everything possible with Moose. 

You are well passed the "new user" stage and it seems normal that you have needs not covered by MooseIDE and that require "programming" in Moose

**Comment by fuhrmanator** [comment]
> can you describe the scenario where you want to know the current state of the bus?
May be we need some kind of new tool?

I was trying to understand how the bus works when changing models (I was debugging the TypeScript models, and made a change and was trying to understand the impact on queries and browsing). Part of the trouble was I couldn't delete models, and I wasn't sure if Moose was displaying the proper results. At one point I had two query browsers with different models on the same bus, which seemed strange. So I started down the rabbit hole with the logger leading to this issue. 

I agree it's not a beginner scenario. Maybe the tool is Pharo itself, to inspect the bus object?

**Comment by LABSARI** [comment]
Actually, a bus has an instance variable 'logger' (instance of MiLogger) that keeps all propagated entities in an ordered collection (screenshot below). The first element of this collection is the entity on the bus (used when a browser is opened on this bus, step 6).
![inspectBus](https://user-images.githubusercontent.com/75275113/187640776-ed3d1100-dd66-41e1-9228-33a73f9712ee.png)

The Logger browser shows this collection and when an entry is removed, it affects the bus logger. Therefore, when the first entry is removed from the logger browser (step 4), the next entry (if there is one) becomes the current entity of the bus.

The browsers (here your first opened Queries browser) registered on that bus are not refreshed with the new (actually old) entity because it could have side effects on your work. If you want to update these browsers with the top entry of the logger, you have to propagate it, using the propagation button of the Logger browser. If the logger is empty (after step 4), you have nothing to propagate from the Logger.

It is not a bug, it just saves you from losing some work on browsers. But since there is the "Freeze" option on browsers, I don't know if this is a needed behavior, it can confuse users. What do you think ?
