### ISSUE TITLE
MooseIDE and Famix are in circular dependency

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/MooseIDE#776]
With [Famix issue #437](https://github.com/moosetechnology/Famix/issues/437) we had to change the generator and the meta-models.

But Famix PR did not pass `testGeneratorsAreUpToDate` because of `FamixCriticBrowserGenerator` in MooseIDE
and MooseIDE PR did not pass some Famix tests as long as the Famix PR was not integrated

I solved it by forcing merge of a failing PR, not very nice :-(

**Comment by badetitou** [comment]
Indeed, it is an important problem IMO

**Comment by ClotildeToullec** [comment]
Wondering if I should close this issue: 
The dependency to Famix is there only for the Critic browser MM.

- The dependency to Famix is declared in MooseIDE baseline only when Famix is not loaded in the image (CI).
- If Famix mm has been modified, `testGeneratorsAreUpToDate` *should* fail when the critic browser is in the image and not up to date. That is why I added testing of external MMs in Famix CI: to inform us of the need to update them (NOT BLOCKING PRs).
- When testing Famix alone, the Critic browser MM is not present (maybe it was at the time this issue was opened?)
