### ISSUE TITLE
Add a search filter to the untagged entities list of the tag browser

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/MooseIDE#981]
In the tag browser we have the list of untagged entities in case we want to tag them by hand. 

It would be nice to be able to filter this list if we look for specific entities.

**Comment by NicolasAnquetil** [comment]
hummm or this is the work for another tool (eg. queryBrowser)
The idea is to do only one thing in each browser and use propagation between tools to combine their behavior.

I started to add tagging facilities in all browsers and I am thinking how to do some simple queries in all tools.
But we must be careful not to put all functionalities in all tools, otherwise they will become un-maintainable.

In this specific case, we could just use a list with a filter at the bottom. This does not cost much and would already help filtering

**Comment by jecisc** [comment]
I was also thinking about the query browser but there is a list of all untagged entities with the possibility to tag them in the tag browser. So I was thinking than a little filter could be useful. 

Or maybe we should not keep this untagged entities list in the tag browser? I don't have a big opinion on that
