### ISSUE TITLE
Speed up distribution map by rejecting untagged entities from clutering

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/MooseIDE#987]
I am trying to produce some distribution maps and some of them are taking a while to compute. 

Most of the time is spent in the clustering algos for the comparisons of floats 

![telegram-cloud-photo-size-4-5832225439899303740-y](https://github.com/moosetechnology/MooseIDE/assets/9519971/c51f28de-c1d7-499a-a0ec-cc3a4d080e7e)

Maybe we could skip the clustering for entities without any tag?

I am not sure about this proposition but this is an idea I have

**Comment by NicolasAnquetil** [comment]
1. The clustering algorithm is inherently O^2
2. it looks strange that we need to adapt float to integer for the comparison ...
3. I don't think that we can skip entities without tag because they have an impact on the clustering, for example outer-entities without tagged inner-entities will be clustered together

**Comment by jecisc** [comment]
I did a speed up of the clustering and this should not have much effect anymore. Closing.
